"""
Reproduce Figures 6 and 7 of the paper:
Distribution of final race positions by solution method (DQN, A2C, TRPO,
PPO, RecurrentPPO) and Grand Prix.

Two evaluation regimes are supported via ``--mode``:

  * ``simulated``  - rivals' decisions and yellow-flag events are randomly
                     generated by the environment (Figure 6).
  * ``real``       - rivals' decisions and yellow-flag events are taken from
                     the actual 2024 race (Figure 7).

The set of nine 2024 GPs and per-GP configurations are imported from
``evaluate_all_gps.py``, keeping a single source of truth for race setup.
QMIP results are not produced by this script - see
``evaluate_qmip_vs_drl.py`` for the QMIP benchmark.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
import config
import compat
compat.setup_all()

import argparse

import numpy as np
import matplotlib.pyplot as plt

from environment.f1_env_all_drivers import create_f1_env_all_drivers
from model_loader import ModelLoader
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

# Reuse all GP configurations and helpers from the existing evaluation script.
from evaluate_all_gps import (
    GP_CONFIGS,
    ALGO_ORDER,
    ALGO_COLORS,
    ALGO_ABBREV,
    ALGO_CLASSES,
    NORM_OBS_KEYS,
    SimResult,
    load_gp_config,
    build_rival_strategies,
    run_single_race,
)


def evaluate_one(
    *, mode: str,
    config_entry: dict,
    algo_name: str,
    loader: ModelLoader,
    n_simulations: int,
    base_seed: int,
) -> list:
    """Run ``n_simulations`` for one (GP, algorithm) under the requested mode."""
    gp_name = config_entry['gp_name']
    agent_driver = config_entry['agent_driver']
    model_dir = config_entry['model_dir']

    gp_cfg = load_gp_config(gp_name)
    initial_positions = gp_cfg['initial_positions_list_2024']
    rival_strategies, initial_compounds = build_rival_strategies(config_entry)

    if mode == 'real':
        eval_mode = True
        laps_vsc = gp_cfg['laps_vsc_2024']
        laps_sc = gp_cfg['laps_sc_2024']
        rival_actions = rival_strategies
    elif mode == 'simulated':
        # eval_mode=False -> env samples yellow flags and rival actions via the
        # logit models; we still want fixed initial positions for fair comparison.
        eval_mode = False
        laps_vsc = []
        laps_sc = []
        rival_actions = {}
    else:
        raise ValueError(f"Unknown mode {mode!r}")

    raw_env = create_f1_env_all_drivers(
        gp=gp_name,
        driver=agent_driver,
        deterministic=False,
        yf_enabled=True,
        initial_positions=initial_positions,
        loader=loader,
        verbose=False,
    )
    raw_env.set_evaluation_mode(
        eval_mode=eval_mode,
        laps_vsc=laps_vsc,
        laps_sc=laps_sc,
        initial_positions=initial_positions,
        rival_actions=rival_actions,
    )

    vec_env = DummyVecEnv([lambda: raw_env])

    model_path = os.path.join(str(config.RL_AGENTS_DIR), model_dir, algo_name, 'best_model.zip')
    if not os.path.exists(model_path):
        print(f"  [{algo_name}] model not found at {model_path}, skipping")
        vec_env.close()
        return []

    vecnorm_path = os.path.join(str(config.RL_AGENTS_DIR), model_dir, algo_name, 'vecnormalize_stats.pkl')
    if os.path.exists(vecnorm_path):
        try:
            vec_env = VecNormalize.load(vecnorm_path, vec_env)
            vec_env.training = False
            vec_env.norm_reward = False
        except (ValueError, AttributeError):
            vec_env = VecNormalize(vec_env, norm_reward=False,
                                   norm_obs_keys=NORM_OBS_KEYS, clip_reward=10000.0)
            vec_env.training = False
    else:
        vec_env = VecNormalize(vec_env, norm_reward=False,
                               norm_obs_keys=NORM_OBS_KEYS, clip_reward=10000.0)
        vec_env.training = False

    AlgoClass = ALGO_CLASSES[algo_name]
    model = AlgoClass.load(model_path, env=vec_env)

    results = []
    for i in range(n_simulations):
        results.append(
            run_single_race(model, vec_env, raw_env, algo_name,
                            seed=base_seed + i,
                            initial_compounds=initial_compounds)
        )
    vec_env.close()
    return results


def plot_grid(all_gp_results, mode: str, output_path: str):
    """3x3 boxplot grid of final positions."""
    n_gps = len(all_gp_results)
    nrows, ncols = 3, 3
    fig, axes = plt.subplots(nrows, ncols, figsize=(15, 12), sharey=True)
    axes_flat = axes.flatten()

    for idx, gp_data in enumerate(all_gp_results):
        ax = axes_flat[idx]
        results = gp_data['results']
        available = [a for a in ALGO_ORDER if a in results and results[a]]
        position_data = [[r.final_position for r in results[a]] for a in available]
        labels = [ALGO_ABBREV.get(a, a) for a in available]

        if position_data:
            bp = ax.boxplot(
                position_data, labels=labels, patch_artist=True,
                showmeans=True,
                meanprops=dict(marker='D', markerfacecolor='red',
                               markeredgecolor='red', markersize=5),
                medianprops=dict(color='black', linewidth=1.5),
            )
            for patch, algo in zip(bp['boxes'], available):
                patch.set_facecolor(ALGO_COLORS.get(algo, '#cccccc'))
                patch.set_alpha(0.75)
                patch.set_edgecolor('black')
                patch.set_linewidth(1)

        starting = gp_data.get('real_starting_pos')
        finishing = gp_data.get('real_finishing_pos')
        if starting is not None:
            ax.axhline(starting, color='red', ls='--', lw=1.2, zorder=0)
        if finishing is not None:
            ax.axhline(finishing, color='blue', ls='--', lw=1.2, zorder=0)

        ax.set_title(gp_data['display_name'], fontsize=10)
        ax.set_ylim(20.5, 0.5)
        ax.set_yticks([1, 4, 8, 12, 16, 20])
        ax.grid(alpha=0.3, axis='y')

    for j in range(n_gps, nrows * ncols):
        axes_flat[j].axis('off')

    fig.text(0.04, 0.5, 'Final Position', ha='center', va='center',
             rotation='vertical', fontsize=12)
    title = ('Final position distribution - fully simulated' if mode == 'simulated'
             else 'Final position distribution - real 2024 race events')
    fig.suptitle(title, fontsize=14, y=0.98)
    fig.tight_layout(rect=[0.05, 0.02, 1, 0.96])

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    fig.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"\nSaved figure to {output_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--mode', choices=['simulated', 'real'], default='simulated',
                        help='Evaluation regime (default: simulated, i.e., Figure 6)')
    parser.add_argument('--gp', default=None,
                        help='Restrict to a single GP (debug); omit to evaluate all 9')
    parser.add_argument('--n-sims', type=int, default=500,
                        help='Number of simulations per (GP, algorithm) (default: 500)')
    parser.add_argument('--base-seed', type=int, default=0,
                        help='Base random seed (default: 0)')
    parser.add_argument('--output', default=None,
                        help='Output PNG path; defaults to figs/figure_{6|7}_*.png')
    args = parser.parse_args()

    if args.output is None:
        suffix = 'simulated' if args.mode == 'simulated' else 'real'
        idx = '6' if args.mode == 'simulated' else '7'
        args.output = f'figs/figure_{idx}_final_position_{suffix}.png'

    loader = ModelLoader(verbose=False)
    configs = GP_CONFIGS if args.gp is None else [
        c for c in GP_CONFIGS if c['gp_name'] == args.gp or c['display_name'] == args.gp
    ]
    if not configs:
        raise SystemExit(f"GP '{args.gp}' not found in GP_CONFIGS")

    all_gp_results = []
    for cfg_entry in configs:
        print(f"\n{'='*70}\nGP: {cfg_entry['display_name']}  -  mode={args.mode}\n{'='*70}")
        gp_results = {}
        for algo in ALGO_ORDER:
            print(f"  -> {algo}")
            res = evaluate_one(
                mode=args.mode,
                config_entry=cfg_entry,
                algo_name=algo,
                loader=loader,
                n_simulations=args.n_sims,
                base_seed=args.base_seed,
            )
            if res:
                gp_results[algo] = res
                positions = [r.final_position for r in res]
                print(f"     mean P{np.mean(positions):.2f}  median P{int(np.median(positions))}  "
                      f"DSQ {sum(1 for r in res if not r.changed_compound)}/{len(res)}")
        gp_cfg = load_gp_config(cfg_entry['gp_name'])
        starting = gp_cfg['initial_positions_2024'].get(cfg_entry['agent_driver'])
        all_gp_results.append({
            'display_name': cfg_entry['display_name'],
            'real_starting_pos': starting,
            'real_finishing_pos': cfg_entry.get('real_finishing_pos'),
            'results': gp_results,
        })

    plot_grid(all_gp_results, args.mode, args.output)


if __name__ == '__main__':
    main()
